{% set version = "1.3-1" %}

package:
  name: r-spatstat.data
  version: {{ version|replace("-", "_") }}

source:
  fn: spatstat.data_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/spatstat.data_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/spatstat.data/spatstat.data_{{ version }}.tar.gz
  sha256: c3ad35677c78aa04e6fb1927aa15abd21ff1fdac58a8b365ce54bc93034b8b8f

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-spatstat.utils
  run:
    - r-base
    - r-spatstat.utils

test:
  commands:
    - $R -e "library('spatstat.data')"  # [not win]
    - "\"%R%\" -e \"library('spatstat.data')\""  # [win]

about:
  home: http
  license: GPL (>= 2)
  summary: Contains all the datasets for the 'spatstat' package.

extra:
  recipe-maintainers:
    - ocefpaf
