{% set version = "3.0-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.data/spatstat.data_{{ version }}.tar.gz
  sha256: 8eeb4b1de356e9cef42f58b5e0fc7ced2a476a1306e09395ba97253b22dd5300

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-spatstat.utils >=3.0_2
  run:
    - r-base
    - r-matrix
    - r-spatstat.utils >=3.0_2

test:
  commands:
    - $R -e "library('spatstat.data')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.data')\""  # [win]

about:
  home: http://www.spatstat.org
  license: GPL-2.0-or-later
  summary: Contains all the datasets for the 'spatstat' package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
