{% set version = "1.4-0" %}

package:
  name: r-spatstat.data
  version: {{ version|replace("-", "_") }}

source:
  fn: spatstat.data_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/spatstat.data_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/spatstat.data/spatstat.data_{{ version }}.tar.gz
  sha256: 121e5bb92beb7ccac920f921e760f429fd71bcfe11cb9b07a7e7326c7a72ec8c

build:
  noarch: generic
  number: 2001
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-spatstat.utils
  run:
    - r-base
    - r-spatstat.utils

test:
  commands:
    - $R -e "library('spatstat.data')"  # [not win]
    - "\"%R%\" -e \"library('spatstat.data')\""  # [win]

about:
  home: http
  license: GPL (>= 2)
  summary: Contains all the datasets for the 'spatstat' package.

extra:
  recipe-maintainers:
    - ocefpaf
