travis:
  secure:
    BINSTAR_TOKEN: wGlE5NwuQvWH7OcDWvCHIh+UrItSsnI0uinmc7EnLpXgSIGImeeMcO85BftDS7waIf1y1FMyLq5W+09892p8+Zc5A+7rNmlgiQiAg1NqC2DsBSUM9EhK07dsjftxkHFecYe8e09T8mhDJ0MS2qmrvsZpdUND4Lcr30YfJJXuakqrL81tFWceqjRuAf7PPc1ZKN43Lx2E+5mqYw75zzJ2Rrg9PL6ACkG5hAMOhQ0Bsfp6XszSzC2LgPVmqx0OZxRoo/yEYMdczE5hjJ7W1dxYGWSncMtvydvoAl/rKsLAhRWgkJyUzcKWWC14zNBu0AGZNvw+xBCv3Kqw3EdVeS0EGTRqhdDcPUZ5NWIjhkKFuxeEzQYfK8JpKJfGfeowu2uw6dQ8dEcLAWM3DhWHji4ws9VmP3PMzRxY1kSwjbQkrIdjYO1DDWJbXLY2NexYt56AF3nYkFl8bPisAcHvh9FEz4A9J9/WFi2N8InBjp6ghFuN6gVWjAy2zt7Cz963hFvUPPG1ckYivH205nIu583STeUidoe/YTKUUKUAVbM9OjqrXkEVIaym4DU3CMqVE8x5E0t00F3w5SqrNmGFgolgjrGRxC6kaLmxrxmkEzhNxMpYC71M70qyVxMckZzXkXpLJzg1ezYR2QIKd39Ti2Sd10nuA5WzQMWcoidrqgbWzKM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
